# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "32689d07bc91c9f737bcc2dfdf2df9a9"
name = "DEV FastEditor"
handle = "dev-fasteditor"
application_url = "https://refined-dassie-concrete.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/gdpr"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/app/orders_paid"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_orders,read_products,write_orders"

[auth]
redirect_urls = ["https://refined-dassie-concrete.ngrok-free.app/auth/callback", "https://refined-dassie-concrete.ngrok-free.app/auth/shopify/callback", "https://refined-dassie-concrete.ngrok-free.app/api/auth/callback"]

[app_proxy]
url = "https://refined-dassie-concrete.ngrok-free.app"
subpath = "embedded"
prefix = "apps"

[pos]
embedded = false
