# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e6d3d94db638b1926bb0c757a913134a"
name = "FastEditor"
handle = "fast-editor-1"
application_url = "https://fasteditor-plugin-gilt.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhook/app/subscriptions/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/app/orders_paid"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/app/gdpr"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_orders,read_products,write_orders"

[auth]
redirect_urls = [
  "https://fasteditor-plugin-gilt.vercel.app/auth/callback",
  "https://fasteditor-plugin-gilt.vercel.app/auth/shopify/callback",
  "https://fasteditor-plugin-gilt.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://fasteditor-plugin-gilt.vercel.app"
subpath = "embedded"
prefix = "apps"

[pos]
embedded = false
