api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "fasteditor-cart-transform"
type = "function"
uid = "df843bd3-c998-3ffb-4886-f5cdd860cef393466e14"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
